# Generated by Django 3.2 on 2021-05-29 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210527_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card',
            field=models.IntegerField(default='1234'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_plan',
            field=models.CharField(choices=[('1', 'Ultimate  100$/m'), ('2', 'Regular 50$/m'), ('3', 'Free 0$/m')], default='Ultimate  100$/m', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
