# Generated by Django 3.2 on 2021-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='0521111111'),
        ),
    ]
